name: ci

on:
  push:
  pull_request:

jobs:
  rust-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo check
        run: cargo check --manifest-path chromsize/Cargo.toml --locked

      - name: Cargo test
        run: cargo test --manifest-path chromsize/Cargo.toml --locked --tests
